# from hdbcli import dbapi
# from hana_ml.dataframe import ConnectionContext
# import pandas as pd
# import os
# from sqlalchemy import create_engine


# conn = dbapi.connect(address="03b7ba32-1aca-46d2-b2ab-7e832d9d8881.hana.trial-us10.hanacloud.ondemand.com",
#                      port=443,user="DBADMIN", password="Acceron@123")
# cursor = conn.cursor()

# print('hi')
# cursor.execute("""CREATE TABLE dbadmin.EMPLOYEE (SN INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,NAME VARCHAR(20),AGE INTEGER,GENDER VARCHAR(10),SALARY DOUBLE)""")
# nm ='govind'
# ag ='37'
# sx ='Male'
# sl ='90000'
#
# sql= "INSERT INTO dbadmin.EMPLOYEE (NAME, AGE, GENDER, SALARY) VALUES ('selvi', '24', 'female', '80000' )"
#
# conn.commit()
# cursor.close()
# conn.close()
import pyhdb

connection = pyhdb.connect(
    host='03b7ba32-1aca-46d2-b2ab-7e832d9d8881.hana.trial-us10.hanacloud.ondemand.com',
    port= 443,  # Default SAP HANA port
    user='DBADMIN',
    password='Acceron@123'
)

cursor = connection.cursor()
print('hi')
cursor.close()

# user = "dbadmin"
# pwd = "Mahadev#1234"
# url = "f6383bda-3140-4b5c-aeae-f926b9df968f.hana.trial-us10.hanacloud.ondemand.com"
# port= 443
# cc = ConnectionContext(url, port, user, pwd)
# # print(cc.hana_version())
# hana_ml_df = cc.table('EMPLOYEE', schema='DBADMIN')
# # hana_ml_df
# # help(hana_ml_df.collect)
# df = hana_ml_df.collect()
# df.head()